number1= int (input('input number = '))
print ('Понеділок')
number2= int (input('input number = '))
print ('Вівторок')
number3= int (input('input number = '))
print ('Середа')
number4= int (input('input number = '))
print('Четвер')
number5= int (input('input number = '))
print('Пятниця')
number6= int (input('input number = '))
print('Субота')
number7= int (input('input number = '))
print('Неділя')
